### ISSUE TITLE
How come Windows never gets any love?

### ISSUE THREAD

**Issue by pauldotknopf** [santinic/how2#28]

**Comment by santinic** [comment]
it's not intentional, I dont have windows :( 
if you want to take care of some porting issues please do

**Comment by Hammster** [comment]
I've run it on windows 10 from cmd and powershell, you have to use return after pressen SPACE though. 
msys2 has a problem with process.stdin.setRawMode(true) also some issues on returning the main function when the spacebar is pressed. Or is there any other issue ?

**Comment by cannap** [comment]
Hi, works fine for me in "cmd" but when i try in cmder it looks like so 
![49adf5ac21f274fda0f92bda1528ab4e](https://cloud.githubusercontent.com/assets/1394151/13272213/c6d78200-da9a-11e5-8243-6383f53422c7.png)


thanks for this usefull tool! i like it

**Comment by Hammster** [comment]
@cannap the issue here is that the unicode range is not sufficent or a offset is shifted.

either way its a problem with https://github.com/chjj/blessed or directly related to cmder i fiddled with the font settings and got it to display the characters right.

**Comment by danielkop** [comment]
Another windows issue is that by default searches go to     
        site = 'site:unix.stackexchange.com';
When running on windows, perhaps it's better to search 
superuser.com

can use this to determine the OS:
var isWin = /^win/.test(process.platform);

**Comment by danyshaanan** [comment]
I think that `require('os').type()` might return a more standard value that will not require a regexp. (but this should be tested and I don't have a windows machine around).

**Comment by danielkop** [comment]
@danyshaanan from the 'os' module's docs:
os.platform()
Returns the operating system platform. Possible values are 'darwin', 'freebsd', 'linux', 'sunos' or 'win32'. Returns the value of process.platform.

the regex is just to avoid checking for both win32 and win64.

**Comment by Kachilero** [comment]
Would just like to comment that MINGW64 also throws an error:
`TypeError: process.stdin.setRawMode is not a function`
as mentioned above. Although it works just fine in Windows PowerShell

**Comment by zQueal** [comment]
@Hammster Could you go into more detail as to what font settings you changed in Cmder to fix the font issues? I'm having this problem now.

![9zzhaxk](https://cloud.githubusercontent.com/assets/239193/13439586/32805308-dfbc-11e5-9b9f-a7e757ec1e29.png)

**Comment by Hammster** [comment]
i really just clicked through everything. The quick solution is if you reset the settings and save them, then restart the program. I try to find the values i changed to get a more precise answer.

**Comment by tildebyte** [comment]
Almost works in Gnome Terminal 3.18 running on latest Cyg/X x64 (Windows 7). First result is retrieved as expected, then I also get `TypeError: process.stdin.setRawMode is not a function`. I'm not so hung up on terminal magic (colors etc.) but the list of results would be nice to have. Thx, btw. This has really nice features compared to e.g. `howdoi`

**Comment by dubiouscript** [comment]
:jack_o_lantern:  :scroll:
